### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by glenpogz36** [Nx-0/Discord-autosender#1]
Hello I cloned your respository. How do I actually run these? Do I need to provide some .env

**Comment by Existential-Kernel** [comment]
you can't really use js packages by cloning them from github, it doesn't really work like that. You must use `npm` to install the package by doing:
```bash
npm i discord-autosender
```
The full instructions are in the [README](https://github.com/Nx-0/Discord-autosender/blob/main/README.md) of the repository. 

Also, I highly recommend you use a `.env` file for sensitive information like your discord token. It's not required but it's recommended even if your code wouldn't be uploaded online on github or any similar platform.

**Comment by glenpogz36** [comment]
do I need to provide these somewhere? 


const autosend = require("discord-autosender")

var message = "This message has been sent from an automated script!"
var channelID = ""
var tokenID = ""

**Comment by Existential-Kernel** [comment]
yes, those 3 variables are required. I don't exactly understand what you mean by "provide" but I'll assume you meant by how to get these values. 


## Getting the channel ID:
The channel ID variable is pretty easy to get. You need to enable developer mode by going into your discord account's setting in the "Advanced" section, then you can need to enable the "developer mode" setting. After that, you need to right click on the channel you want the script to post in, and click on "copy id", this will copy the channel's id into your clipboard. You can view a tutorial [here](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) for further information.


## Getting your account's discord token:
This is a bit more challenging, but not impossible. I won't go my way to explain how to do it step by step since it'll take me a lot of time but I highly recommend you watch [this](https://www.youtube.com/watch?v=YEgFvgg7ZPI) video that goes through it in detail.

**Comment by glenpogz36** [comment]
How Do I run more than once or loop?

**Comment by Existential-Kernel** [comment]
You can loop by using the built in `PostLoop` function. Here's an example of how to use:

```
const autosend = require("discord-autosender")

var minimum = 1000
var maximum = 2000
var message = "This message has been sent from an automated script!"
var channelID = "945821788531732500"
var tokenID = "mfa.HrKVKI8EIvRCSTrrfvNL6x9yp9jRDyvheux8PjwUCBigMVDdn8vRFw3GgfGxbB2pAvYOnGa7cJw2BPVZk-KJ"

autosend.PostLoop(message, channelID, tokenID, minimum, maximum)
```
The `minimum` and `maximum` variables are the range of milliseconds for your posting script to loop. So the above example means "loop indefinitely with each message having a delay of 1 to 2 seconds"
The reason why the minimum and maximum parameters are a thing is to avoid detection from discord because it could potentially flag suspicious behavior if you send a message every 1 second down to the millisecond precision and assume it's a script, which is against discord's ToS.

**Comment by Existential-Kernel** [comment]
I'm going to assume everything works fine, please comment to reopen this issue if you need any more help :)
